### ISSUE TITLE
can't modify frozen String

### ISSUE THREAD

**Issue by davidjbradshaw** [causes/scss-lint#399] opened 2015-03-20 14:12 UTC
I'm getting this error when I try and run this on ruby 1.9.3p286 (2012-10-12 revision 37165) [x86_64-darwin12.2.0].

	==> scss-lint cdn/styles/
	can't modify frozen String
	/Users/dave/.rvm/gems/ruby-1.9.3-p286/gems/scss-lint-0.34.0/lib/scss_lint/engine.rb:26:in `force_encoding'
	/Users/dave/.rvm/gems/ruby-1.9.3-p286/gems/scss-lint-0.34.0/lib/scss_lint/engine.rb:26:in `initialize'
	/Users/dave/.rvm/gems/ruby-1.9.3-p286/gems/scss-lint-0.34.0/lib/scss_lint/runner.rb:33:in `new'
	/Users/dave/.rvm/gems/ruby-1.9.3-p286/gems/scss-lint-0.34.0/lib/scss_lint/runner.rb:33:in `find_lints'
	/Users/dave/.rvm/gems/ruby-1.9.3-p286/gems/scss-lint-0.34.0/lib/scss_lint/runner.rb:21:in `block in run'
	/Users/dave/.rvm/gems/ruby-1.9.3-p286/gems/scss-lint-0.34.0/lib/scss_lint/runner.rb:20:in `each'
	/Users/dave/.rvm/gems/ruby-1.9.3-p286/gems/scss-lint-0.34.0/lib/scss_lint/runner.rb:20:in `run'
	/Users/dave/.rvm/gems/ruby-1.9.3-p286/gems/scss-lint-0.34.0/lib/scss_lint/cli.rb:51:in `scan_for_lints'
	/Users/dave/.rvm/gems/ruby-1.9.3-p286/gems/scss-lint-0.34.0/lib/scss_lint/cli.rb:45:in `act_on_options'
	/Users/dave/.rvm/gems/ruby-1.9.3-p286/gems/scss-lint-0.34.0/lib/scss_lint/cli.rb:24:in `run'
	/Users/dave/.rvm/gems/ruby-1.9.3-p286/gems/scss-lint-0.34.0/bin/scss-lint:6:in `<top (required)>'
	/Users/dave/.rvm/gems/ruby-1.9.3-p286/bin/scss-lint:23:in `load'
	/Users/dave/.rvm/gems/ruby-1.9.3-p286/bin/scss-lint:23:in `<main>'
	/Users/dave/.rvm/gems/ruby-1.9.3-p286/bin/ruby_executable_hooks:15:in `eval'
	/Users/dave/.rvm/gems/ruby-1.9.3-p286/bin/ruby_executable_hooks:15:in `<main>'
	Report this bug at https://github.com/causes/scss-lint/issues

**Comment by sds** [comment] 2015-03-20 17:08
Duplicate of #390, which was fixed by b0de02f.

**Closed by sds** 2015-03-20 17:08 UTC
Labels: duplicate

**Comment by davidjbradshaw** [comment] 2015-03-20 19:16
I installed the latest version of this via `gem install scss-lint` today and that still has this issue. How do I get the version with the fix in it?

**Comment by sds** [comment] 2015-03-20 20:25
Which version are you running? The latest version 0.35.0 was just released today.

**Comment by davidjbradshaw** [comment] 2015-03-23 11:32
Ok just did an update and it's fixed now.

Thanks.
