### ISSUE TITLE
Lint reports on using color map-key as function parameter

### ISSUE THREAD

**Issue by bartveneman** [causes/scss-lint#344] opened 2015-01-19 15:08 UTC
````scss
// _vars.scss
$colors: (
  blue: #0000ff,
  red: #ff0000
);
````
````scss
// _functions.scss
@function color($name) {
  @return map-get($colors, $name);
}
````
````scss
// main.scss
.myElement {
  color: color(red);
}
````
Scss-lint now reports an error on `main.scss` because `ColorKeyword: Color 'red' should be written in hexadecimal form as '#ff0000'`. I might be missing something, but I don't think this is desirable behaviour.

**Comment by lencioni** [comment] 2015-01-19 16:14
Thanks for the report @bartveneman. However, I think this is a duplicate of #175.

**Closed by lencioni** 2015-01-19 16:14 UTC

**Comment by bartveneman** [comment] 2015-01-19 18:50
You're absolutely right. Sorry about that.

**Comment by lencioni** [comment] 2015-01-19 18:51
No worries! Thanks for the report!
